name: SAST

on:
  push:
    branches:
      - dev/master
  pull_request:
    branches:
      - dev/master

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Set the Python version you are using

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit


      - name: Run Bandit # Criticality higher than medium and confidence level set to high
        run: |
          bandit -r -ll -iii src/
