name: Merge to Master on Success

on:
  push:
    branches:
      - dev/master  # Only doing this if the code is pushed to dev/master

jobs:
  merge_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Setting the python version to 3.10

      - name: Install dependencies
        run: pip install -r src/requirements.txt  # For now the requirements.txt file is in the "src" directory

      - name: Install Black  # Installing black
        run: pip install black

      - name: Check code formatting with Black
        run: black --check --diff src  # Checking the codebased with linter

