name: Merge to Master on Success

on:
  push:
    branches:
      - dev/master  # Only doing this if the code is pushed to dev/master

jobs:
  merge_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Setting the python version to 3.10

      - name: Install dependencies
        run: pip install -r src/requirements.txt  # For now the requirements.txt file is in the "src" directrory

      - name: Install Black  # Installing black
        run: pip install black

      # - name: Run unit tests
      #  run: python -m unittest discover  # Will have to adjust this command

      - name: Check code formatting with Black
        run: black --check src/Collectors  # Adjust this command based on your codebase

      - name: Merge to Master on Success
        if: success()  # Only proceed if the previous steps were successful
        run: |
